modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Dark-Utilities/issues"

[[mods]]
modId="darkutils"
version="${version}"
displayName="Dark Utilities"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.darkutilities]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.darkutilities]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.5.33,)"
    ordering="AFTER"
    side="BOTH"