modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Dark-Utilities/issues"

[[mods]]
modId="darkutils"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.darkutilities]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.darkutilities]]
    modId="bookshelf"
    mandatory=true
    versionRange="[4.1.31]"
    ordering="NONE"
    side="BOTH"