modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Dark-Utilities/issues"

[[mods]]
modId="darkutils"
updateJSONURL="https://updates.blamejared.com/get?n=darkutils&gv=1.16.1"
version="${version}"
displayName="Dark Utilities"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.darkutilities]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.darkutilities]]
    modId="bookshelf"
    mandatory=true
    versionRange="[6.1.11,)"
    ordering="AFTER"
    side="BOTH"